export type Applicant = {
    id: number
    name: string
    role: string
    tags: string[]
    summary: string
    photoInitial: string
}

export const APPLICANTS: Applicant[] = [
    {
        id: 1,
        name: '하시모토 예링',
        role: '프론트엔드 요정 엔지냥',
        photoInitial: 'YR',
        tags: ['#frontend냥', '#ts츄릅', '#반짝반짝UI'],
        summary: '숨겨진 DOM까지 반짝반짝 정리해주는 요정이래요오~! 오늘도 예쁜 화면 만들기 힘낼게요옹♡',
    },
    {
        id: 2,
        name: '쿠로사와 지오냥',
        role: '백엔드 쿠로마도쨩',
        photoInitial: 'ZN',
        tags: ['#backend', '#마계API', '#쿠로복구'],
        summary: '서버가 아프면 마력으로 토닥여주는 쿠로마도사에요오…♡ 밤새 안정화? 문제없다냥!',
    },
    {
        id: 3,
        name: '미카미 사뇨뇨',
        role: 'UX 음양무녀쨩',
        photoInitial: 'SY',
        tags: ['#design', '#UX무녀', '#UI부적'],
        summary: '사용자의 흐름을 귀신보다 먼저 알아채는 음양 무녀에요! 좋은 경험 만들고 싶다냥~',
    },
    {
        id: 4,
        name: '토오루 미나밍',
        role: '풀스택 만능기사쨩',
        photoInitial: 'TM',
        tags: ['#fullstack', '#react기사단', '#nestjs기사도'],
        summary: '프론트도 백도 내가 전부 지켜줄게요옹! 믿고 맡겨줘요 기사답게 척척~!',
    },
    {
        id: 5,
        name: '아이카와 율리링',
        role: '프론트엔드 춤추는요정쨩',
        photoInitial: 'YR',
        tags: ['#frontend', '#애니슝슝', '#access쪼아요'],
        summary: '애니메이션으로 화면에 생명을 불어넣는 춤추는 요정이에요오~ 반짝반짝해줘볼까나?♡',
    },
    {
        id: 6,
        name: '카미조 지훈훈',
        role: '데이터 연금요정',
        photoInitial: 'JH',
        tags: ['#data', '#파이프키득', '#airflow퐁'],
        summary: '데이터 흐름을 금속처럼 반짝하게 정제하는 알케미스트! 오늘도 자동화 마법 샤라랑~✨',
    },
    {
        id: 7,
        name: '오오카미 세리냥',
        role: '프론트엔드 늑대아이쨩',
        photoInitial: 'SR',
        tags: ['#frontend', '#성능킁킁', '#webpack하울'],
        summary: '성능 문제는 다 알아맞혀버리는 늑대 귀 쫑긋! 냄새만 맡아도 병목 알 수 있다구~ ♡',
    },
    {
        id: 8,
        name: '나카하라 도도링',
        role: '모바일 차원여행자쨩',
        photoInitial: 'DH',
        tags: ['#ios', '#android', '#react이계'],
        summary: '하나의 코드로 여러 세계를 여행하는 차원 아이에요오~ 어디든 텔레포트 해줄게요!',
    },
    {
        id: 9,
        name: '유노 다에에',
        role: 'QA 정화무녀쨩',
        photoInitial: 'DE',
        tags: ['#qa', '#테스트정화', '#자동화찰칵'],
        summary: '버그를 정화! 불순물 제거! 테스트 의식 시작이냥~♡ 안정성은 내 천직인 거 알지?',
    },
    {
        id: 10,
        name: '쿠가 데이카쨩',
        role: 'ML 초능력 로리마도링',
        photoInitial: 'DK',
        tags: ['#ml', '#pytorch영력', '#pipeline영맥'],
        summary: '모델 실험부터 서빙까지 초능력으로 연결시켜버리는 영력 천재 로리 마도사에요오~',
    },
    {
        id: 11,
        name: '스가와라 지스밍',
        role: '프로젝트 무녀링(PM)',
        photoInitial: 'JS',
        tags: ['#pm', '#communication미미', '#신탁로드맵'],
        summary: '팀의 기운을 읽고 모두를 화합하게 만드는 무녀 PM이에요! 다 같이 웃을 수 있게 할게요옹♡',
    },
    {
        id: 12,
        name: '시라누이 현우운',
        role: '백엔드 검객오빠',
        photoInitial: 'HW',
        tags: ['#backend', '#spring검법', '#database참'],
        summary: '서버를 위협하는 트래픽의 파동… 내가 다 베어버릴게. 지켜줄게, 너의 서버…♡',
    },
    {
        id: 13,
        name: '아마미 하늘링',
        role: '프론트엔드 규율요정쨩',
        photoInitial: 'HN',
        tags: ['#frontend', '#vue요정단', '#designsystem경비'],
        summary: '디자인 시스템을 신성하게 지키는 규율요정! 어지르면 혼난다요? 흐잉~!',
    },
    {
        id: 14,
        name: '오토하 지연연',
        role: '프로덕트 환상연성가',
        photoInitial: 'JY',
        tags: ['#design', '#리서치환상', '#prototype뾰로롱'],
        summary: '리서치 결과를 환상처럼 구현하는 몽환 디자이너에요오~! 반짝반짝 보여줄게요♡',
    },
    {
        id: 15,
        name: '후지사키 성준쿤',
        role: 'SRE 방패기사님',
        photoInitial: 'SJ',
        tags: ['#sre', '#observability눈동자', '#infra호위'],
        summary: '인프라를 위해서라면 내가 방패가 될게. 다운타임? 내 앞에선 허락 안 해♡',
    },
    {
        id: 16,
        name: '모리 정인쨩',
        role: '데이터 운명점술사',
        photoInitial: 'JI',
        tags: ['#data', '#analytics점괘', '#sql예언'],
        summary: '데이터를 읽고 미래를 점치는 점술사예요! 흐름이… 보여요…! (반짝)',
    },
    {
        id: 17,
        name: '츠키시마 유나냥',
        role: '마케팅 마법소녀',
        photoInitial: 'YN',
        tags: ['#marketing', '#growth마법진', '#performance☆'],
        summary: '성장을 위해선 실험! 실험! 또 실험! 마법소녀 유나가 퍼포먼스를 높여줄게요♡',
    },
    {
        id: 18,
        name: '사가라 지훈훈',
        role: '백엔드 기계닌자쨩',
        photoInitial: 'JH',
        tags: ['#backend', '#go술식', '#micro忍術'],
        summary: '마이크로서비스를 조용히 다루는 그림자 닌자~ 서버는 이미 내 손 안에 있다냥!',
    },
    {
        id: 19,
        name: '아즈사 소미밍',
        role: '프론트엔드 얼음마녀쨩',
        photoInitial: 'SM',
        tags: ['#frontend', '#nextjs얼음', '#ssr빙글빙글'],
        summary: '빠른 SSR로 웹을 차갑게 최적화하는 얼음 속성 마녀예요~ 시원하게 해주쟝?',
    },
    {
        id: 20,
        name: '쿠사카 미나토링',
        role: '모바일 아키마도사',
        photoInitial: 'MT',
        tags: ['#android', '#kotlin룬', '#architecture마도진'],
        summary: '안정적인 앱 구조는 마법진처럼 섬세해야 해요! 미나토링이 그려줄게요…♡',
    },
    {
        id: 21,
        name: '시노노메 가으응',
        role: '프로덕트 기계요정',
        photoInitial: 'GE',
        tags: ['#design', '#system코기코기', '#component톱니'],
        summary: '컴포넌트 톱니톱니를 딱 맞게 조립하는 기계요정이에요! 부서지면 슬퍼요오 ｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡',
    },
    {
        id: 22,
        name: '카게야마 해잉',
        role: '데이터 성당기사냥',
        photoInitial: 'HI',
        tags: ['#data', '#warehouse성당', '#etl랜스'],
        summary: '데이터 성당의 질서를 지키는 엄격하지만 다정한 기사님♡ 쿼리 비용? 내가 줄여줄게요.',
    },
    {
        id: 23,
        name: '아마츠 다현냥',
        role: '프론트엔드 예지실험소녀',
        photoInitial: 'DH',
        tags: ['#frontend', '#testing예지', '#storybook☆'],
        summary: 'UI 테스트로 미래를 보는 예지소녀에요! 미리 스냅샷 찍어놓을게요옹~♡',
    },
    {
        id: 24,
        name: '쿠로키 도윤욘',
        role: '백엔드 수호령',
        photoInitial: 'DY',
        tags: ['#backend', '#security수호', '#auth결계'],
        summary: '인증 결계를 만들고 지켜주는 수호령이에요오! 무단 접근하면 호되게 혼낸다구?!',
    },
    {
        id: 25,
        name: '세리자와 유리뇽',
        role: '프로덕트 점성PM쨩',
        photoInitial: 'YR',
        tags: ['#pm', '#discovery별점', '#prioritization운명'],
        summary: '프로젝트의 운세를 점치는 점성 PM! 오늘의 우선순위… 두근두근 알려줄게요♡',
    },
    {
        id: 26,
        name: '히라메키 한별링',
        role: '프론트엔드 미학요정',
        photoInitial: 'HB',
        tags: ['#frontend', '#css미적감각', '#layout팔랑팔랑'],
        summary: '레이아웃을 누구보다 예쁘고 조화롭게 만드는 미학요정이에요! 애지중지 다듬을게요~!',
    },
    {
        id: 27,
        name: '아사히 지후후',
        role: '데브옵스 그림자요정쨩',
        photoInitial: 'JH',
        tags: ['#devops', '#ci암흑', '#cd순간이동'],
        summary: '배포 파이프라인을 뒤에서 살짝~ 손봐주는 그림자 요정이에요. 티 안 나지만 열심히 한다구요~',
    },
    {
        id: 28,
        name: '노가미 서혀언',
        role: '데이터 스카우트요정',
        photoInitial: 'SH',
        tags: ['#data', '#dashboard비행', '#bi관측'],
        summary: '대시보드를 타고 휘릭~ 비즈니스 지표를 정찰하는 스카우트 요정! 보고서도 귀엽게 써줄게요♡',
    },
    {
        id: 29,
        name: '타치바나 지밍밍',
        role: '프론트엔드 마도공학소녀',
        photoInitial: 'JM',
        tags: ['#frontend', '#storybook마도서', '#designsystem공방'],
        summary: '디자이너와 함께 마도 컴포넌트를 만드는 공학소녀! 완성되면 자랑해도 돼? 히힛~',
    },
    {
        id: 30,
        name: '키가미 서유윰',
        role: '머신러닝 천재요정쨩',
        photoInitial: 'SY',
        tags: ['#ml', '#llm정령', '#infra마력'],
        summary: '모델 서빙 인프라를 정령들과 함께 만드는 천재 요정이에요♡ 피드백 루프도 찰떡!',
    },
]
